import type { AppState, Wine } from "../types";

// A demo cellar so the app is beautiful and useful the moment it opens — no
// empty shelves. Dates are relative to "now" so the cellar always feels live.

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86400000).toISOString();
}

const wines: Wine[] = [
  {
    id: "w-barolo",
    name: "Barolo Riserva",
    producer: "Giacomo Conterno",
    vintage: 2016,
    varietal: "Nebbiolo",
    region: "Piedmont",
    country: "Italy",
    color: "red",
    photo: null,
    notes: "Anniversary bottle. Rose petal, tar, dried cherry. Needs decanting.",
    likes: "That haunting perfume and the way the tannins are firm but polished.",
    likeTags: ["red fruit", "earthy", "structured"],
    rating: 5,
    price: 180,
    taste: { body: 5, sweetness: 1, tannin: 4, acidity: 5 },
    status: "rack",
    pairing: "Braised beef, truffle pasta",
    createdAt: daysAgo(40),
  },
  {
    id: "w-sancerre",
    name: "Sancerre 'Les Monts Damnés'",
    producer: "Henri Bourgeois",
    vintage: 2022,
    varietal: "Sauvignon Blanc",
    region: "Loire",
    country: "France",
    color: "white",
    photo: null,
    notes: "Flinty, grapefruit, wet stone. So electric on a warm evening.",
    likes: "Razor-sharp acidity and the mineral finish.",
    likeTags: ["citrus", "mineral", "crisp"],
    rating: 5,
    price: 32,
    taste: { body: 2, sweetness: 1, tannin: 1, acidity: 5 },
    status: "rack",
    pairing: "Goat cheese, oysters",
    createdAt: daysAgo(22),
  },
  {
    id: "w-rioja",
    name: "Rioja Reserva",
    producer: "Muga",
    vintage: 2018,
    varietal: "Tempranillo",
    region: "Rioja",
    country: "Spain",
    color: "red",
    photo: null,
    notes: "Leather, dried fig, vanilla from American oak. Great value.",
    likes: "Savory leather note and how smooth it drinks.",
    likeTags: ["red fruit", "leather", "smoky"],
    rating: 4,
    price: 28,
    taste: { body: 4, sweetness: 1, tannin: 3, acidity: 4 },
    status: "rack",
    pairing: "Lamb chops, manchego",
    createdAt: daysAgo(15),
  },
  {
    id: "w-champagne",
    name: "Brut Réserve",
    producer: "Pol Roger",
    vintage: null,
    varietal: "Chardonnay / Pinot Noir",
    region: "Champagne",
    country: "France",
    color: "sparkling",
    photo: null,
    notes: "Brioche, green apple, fine persistent bead.",
    likes: "Toasty depth with crisp apple. Celebration in a glass.",
    likeTags: ["citrus", "brioche", "crisp"],
    rating: 5,
    price: 65,
    taste: { body: 2, sweetness: 2, tannin: 1, acidity: 5 },
    status: "rack",
    pairing: "Oysters, fried chicken",
    createdAt: daysAgo(8),
  },
  {
    id: "w-brunello-wish",
    name: "Brunello di Montalcino",
    producer: "Biondi-Santi",
    vintage: 2017,
    varietal: "Sangiovese",
    region: "Tuscany",
    country: "Italy",
    color: "red",
    photo: null,
    notes: "The benchmark Brunello. Saving up for a special bottle.",
    likes: "Heard it's all about elegance and dried-cherry depth — my style.",
    likeTags: ["dark fruit", "earthy", "structured"],
    rating: 0,
    price: 250,
    taste: { body: 5, sweetness: 1, tannin: 4, acidity: 4 },
    status: "wishlist",
    pairing: "Bistecca alla fiorentina",
    createdAt: daysAgo(5),
  },
  {
    id: "w-riesling-wish",
    name: "Riesling Spätlese",
    producer: "Joh. Jos. Prüm",
    vintage: 2021,
    varietal: "Riesling",
    region: "Mosel",
    country: "Germany",
    color: "white",
    photo: null,
    notes: "Want to explore off-dry German Riesling.",
    likes: "Curious about that sweet/acid tension everyone raves about.",
    likeTags: ["stone fruit", "floral", "zesty"],
    rating: 0,
    price: 40,
    taste: { body: 2, sweetness: 3, tannin: 1, acidity: 5 },
    status: "wishlist",
    pairing: "Thai curry, pork belly",
    createdAt: daysAgo(2),
  },
];

export function buildSeed(): AppState {
  return { wines, outings: [] };
}
